### ISSUE TITLE
Implement missing MicroPython features

### ISSUE THREAD

**Issue by rdagger** [nakagami/nmongo#1]
Do you have plans to implement ssl, authentication, datetime.datetime, and time.struct_time for MicroPython?

**Comment by nakagami** [comment]
No plan.
Does MicroPython has thease package supports ?

**Comment by rdagger** [comment]
Sorry for the slow response.  Micropython does have built-in ssl and hashlib libraries.  Also there are packages available from [Micropython-lib](https://github.com/micropython/micropython-lib) for base64, hmac, datetime and time with "real" struct_time.

**Comment by nakagami** [comment]
Thaks, I will implement some of missing features.

**Comment by rdagger** [comment]
Thanks

**Comment by nakagami** [comment]
For auth() method, these module functions need but not implemented in micropytohn.

- hashlib.pbkdf2_hmac
- hashlib.md5

**Comment by rdagger** [comment]
Looks like hashlib supports sha256.
Would it be possible to use SCRAM-SHA-256 instead of SCRAM-SHA-1?

Looks like the Mongo Python [driver](https://github.com/mongodb/mongo-python-driver/blob/a22719853e9d3d786813a6abdffca3df94bd1e37/pymongo/auth.py) provides an implentation of pbkdf2_hmac:
```
        def _hi(hash_name, data, salt, iterations):
            """A simple implementation of PBKDF2-HMAC."""
            mac = hmac.HMAC(data, None, getattr(hashlib, hash_name))

            def _digest(msg, mac=mac):
                """Get a digest for msg."""
                _mac = mac.copy()
                _mac.update(msg)
                return _mac.digest()

            from_bytes = _from_bytes
            to_bytes = _to_bytes

            _u1 = _digest(salt + b'\x00\x00\x00\x01')
            _ui = from_bytes(_u1, 'big')
            for _ in range(iterations - 1):
                _u1 = _digest(_u1)
                _ui ^= from_bytes(_u1, 'big')
            return to_bytes(_ui, mac.digest_size, 'big')
```

**Comment by nakagami** [comment]
Authentication is available in version 0.4.1.

micropython-datetime is not work, I hope implement to fetch datetime type  data after micropython-datetime released.

**Comment by rdagger** [comment]
I tried both the latest Micropython.org build and the latest Lobo MicroPython build and had an error upon connect:
```
>>> import nmongo
>>> db = nmongo.connect('mongodb://ds123456.mlab.com:41641', 'database1', user='john', password='password123')
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x4010a94e  PS      : 0x00060130  A0      : 0x800f57cd  A1      : 0x3ffdb970  
A2      : 0x3f8148a0  A3      : 0x3ffcdeb8  A4      : 0x00000002  A5      : 0x00000002  
A6      : 0x00000000  A7      : 0x00000001  A8      : 0x00000000  A9      : 0x3ffdb950  
A10     : 0x00000038  A11     : 0x3ffdb970  A12     : 0x00000002  A13     : 0x00000002  
A14     : 0x00000001  A15     : 0x00000000  SAR     : 0x00000000  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000014  LBEG    : 0x4009e268  LEND    : 0x4009e296  LCOUNT  : 0xffffffff  

Backtrace: 0x4010a94e:0x3ffdb970 0x400f57ca:0x3ffdb9a0 0x400f1231:0x3ffdb9c0 0x400f1299:0x3ffdb9e0 0x400fe566:0x3ffdba00 0x400f58f0:0x3ffdbaa0 0x400f1231:0x3ffdbad0 0x400f1299:0x3ffdbaf0 0x400fa56b:0x3ffdbb10 0x400fa2d7:0x3ffdbb60 0x400f1231:0x3ffdbb80 0x400fe4d3:0x3ffdbba0 0x400f58f0:0x3ffdbc40 0x400f1231:0x3ffdbc70 0x400f1299:0x3ffdbc90 0x400fe566:0x3ffdbcb0 0x400f58f0:0x3ffdbd50 0x400f1231:0x3ffdbdd0 0x400f125e:0x3ffdbdf0 0x400e2d24:0x3ffdbe10 0x400e2fa0:0x3ffdbec0 0x400d5d9c:0x3ffdbf00

CPU halted.
```

**Comment by nakagami** [comment]
thanks,
I think It's lack of memory 😢 
I want someone's help to decrease memory usage.

**Comment by nakagami** [comment]
micropythn package datetime.datetime and time.struct_time are now supported by micropythonlib.
But datetime.datetime needs patch, now.
https://github.com/nakagami/nmongo/blob/master/tzinfo.patch

- ssl move to issue #2
- authentication methods move to issue #3
